#!/usr/bin/env bash
# DESCRIPTION
#   Automatic proxy opening based on sshuttle
#
# USAGE
#	  sudo proxy start username server port
#
# AUTHOR
# 	Credit for the original script go to Salem Harrache's article:
#	    http://salem.harrache.info/proxy-socks-partout.html

name=proxy

user="${1:username}"
host="${2:sshserver}"
port=${3:22}

pidFile="$HOME"/.local/var/run/$name
mkdir -p "$(dirname "$pidFile")"

# Arrêt du service
function stop {
  if [[ -f "$pidFile" ]] ; then
    echo -n "Arrêt de $name..."
    kill -9 $(cat "$pidFile")
    rm "$pidFile"
    echo "OK"
  fi
}

# Démarrage du service
function start {
  echo -n "Démarrage de $name..."
  sshuttle -r $user@$host:$port 0/0 --dns -D --pidfile "$pidFile"
  echo "OK"
}

# commandes
case $1 in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    stop
    start
    ;;
    *)
    echo "usage: $(basename $0) start|stop"
    exit 1
esac
